version: '3.1'
services:
  manicure:
    image: 'manicure:latest'
    build: .
    container_name: manicure
    depends_on:
      - ms-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ms-db:5432/manicure
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"

  ms-db:
    image: postgres:14-alpine
    container_name: ms-db
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_DB=manicure
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
