CREATE TABLE IF NOT EXISTS users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(100)                            NOT NULL,
    last_name  VARCHAR(100)                            NOT NULL,
    patronymic VARCHAR(100),
    email      VARCHAR(200)                            NOT NULL,
    phone      VARCHAR(30)                             NOT NULL,
    birthday   DATE                                    NOT NULL,
    is_master   BOOLEAN                                 NOT NULL,
    CONSTRAINT PK_USER PRIMARY KEY (id),
    CONSTRAINT UNIQUE_USER_EMAIL UNIQUE (email),
    CONSTRAINT UNIQUE_USER_PHONE UNIQUE (phone)
);

CREATE TABLE IF NOT EXISTS procedures
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    procedure_name VARCHAR(100),
    description    VARCHAR(5000),
    CONSTRAINT PK_PROCEDURE PRIMARY KEY (id),
    CONSTRAINT UNIQUE_PROCEDURE_NAME UNIQUE (procedure_name)
);

CREATE TABLE IF NOT EXISTS appointments
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    client_id       BIGINT                                  NOT NULL,
    master_id       BIGINT                                  NOT NULL,
    procedure_id    BIGINT                                  NOT NULL,
    start_date_time TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_date_time   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    status          VARCHAR(100),
    CONSTRAINT PK_APPOINTMENT PRIMARY KEY (id),
    CONSTRAINT FK_CLIENT_ON_USER FOREIGN KEY (client_id) REFERENCES users (id),
    CONSTRAINT FK_MASTER_ON_USER FOREIGN KEY (master_id) REFERENCES users (id),
    CONSTRAINT FK_PROCEDURE_ID_ON_PROCEDURE FOREIGN KEY (procedure_id) REFERENCES procedures (id)
);

CREATE TABLE IF NOT EXISTS comments
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id        BIGINT                                  NOT NULL,
    appointment_id BIGINT                                  NOT NULL,
    user_text      VARCHAR(5000),
    created        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT PK_COMMENT PRIMARY KEY (id),
    CONSTRAINT FK_COMMENTATOR_ON_USER FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT FK_APPOINTMENT_ID_ON_APPOINTMENT FOREIGN KEY (appointment_id) REFERENCES appointments (id) ON DELETE CASCADE
);